"""Install and provision a portable MariaDB instance under ~/.tmsm/mariadb."""
from __future__ import annotations

import secrets
import shutil
import subprocess
import time
from pathlib import Path
from typing import Callable

from .. import config, downloads, paths

Log = Callable[[str], None]


_MY_CNF_TEMPLATE = """# Auto-generated by tmsm
[mysqld]
datadir = {datadir}
socket  = {socket}
port    = {port}
bind-address = {bind}
skip-name-resolve
default-storage-engine = InnoDB
innodb_file_per_table = 1
innodb_flush_log_at_trx_commit = 2
innodb_buffer_pool_size = 256M
max_connections = 200
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

[client]
socket = {socket}
port   = {port}
"""


def is_installed() -> bool:
    return (paths.MARIADB_DIST / "bin" / "mysqld").is_file()


def _find_top_dir(extract_dir: Path) -> Path:
    """Tarballs unpack to a single top-level dir; find it."""
    entries = [p for p in extract_dir.iterdir()]
    if len(entries) == 1 and entries[0].is_dir():
        return entries[0]
    return extract_dir


def _bin(name: str) -> Path:
    return paths.MARIADB_DIST / "bin" / name


def install_mariadb(log: Log) -> None:
    """Download portable MariaDB, init datadir, set root password, save it to config."""
    if is_installed():
        log("MariaDB already installed.")
        return

    cfg = config.load()
    url = cfg.downloads.mariadb_url

    paths.MARIADB_DIR.mkdir(parents=True, exist_ok=True)
    cache_dir = paths.HOME / "cache"
    archive = cache_dir / Path(url).name
    if archive.exists():
        log(f"Using cached download: {archive}")
    else:
        downloads.download(url, archive, log)

    if paths.MARIADB_DIST.exists():
        log(f"Cleaning previous dist dir {paths.MARIADB_DIST}")
        shutil.rmtree(paths.MARIADB_DIST)
    paths.MARIADB_DIST.mkdir(parents=True, exist_ok=True)

    # Extract, then move contents of the single top-level dir up into DIST.
    tmp = paths.MARIADB_DIR / ".extract"
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir()
    downloads.extract_tar(archive, tmp, log)
    top = _find_top_dir(tmp)
    for entry in top.iterdir():
        shutil.move(str(entry), str(paths.MARIADB_DIST / entry.name))
    shutil.rmtree(tmp)

    mysqld = _bin("mysqld")
    if not mysqld.is_file():
        raise RuntimeError(f"Extracted archive has no bin/mysqld at {paths.MARIADB_DIST}")

    # my.cnf
    my_cnf = paths.MARIADB_DIR / "my.cnf"
    my_cnf.write_text(_MY_CNF_TEMPLATE.format(
        datadir=paths.MARIADB_DATA,
        socket=paths.MARIADB_DIR / "mysql.sock",
        port=cfg.mariadb.port,
        bind=cfg.mariadb.host,
    ))
    log(f"Wrote {my_cnf}")

    # Initialize datadir
    if paths.MARIADB_DATA.exists() and any(paths.MARIADB_DATA.iterdir()):
        log(f"Datadir at {paths.MARIADB_DATA} already populated, skipping init.")
    else:
        paths.MARIADB_DATA.mkdir(parents=True, exist_ok=True)
        _init_datadir(my_cnf, log)

    # Generate root password and apply it via a one-shot bootstrap.
    root_pw = cfg.mariadb.root_password or secrets.token_urlsafe(18)
    _set_root_password(my_cnf, root_pw, log)

    cfg.mariadb.root_password = root_pw
    config.save(cfg)
    _write_root_pw_file(root_pw)
    log("Saved MariaDB root password to ~/.tmsm/config.toml and mariadb/root.pw")
    log("MariaDB installed.")


def _root_pw_file() -> Path:
    return paths.MARIADB_DIR / "root.pw"


def _write_root_pw_file(pw: str) -> None:
    p = _root_pw_file()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(pw)
    try:
        p.chmod(0o600)
    except OSError:
        pass


def delete_mariadb(log: Log) -> None:
    """Remove MariaDB install + datadir + saved root password."""
    import shutil
    if paths.MARIADB_DIR.exists():
        log(f"Removing {paths.MARIADB_DIR}")
        shutil.rmtree(paths.MARIADB_DIR)
    else:
        log(f"{paths.MARIADB_DIR} does not exist, nothing to remove.")
    cfg = config.load()
    if cfg.mariadb.root_password:
        cfg.mariadb.root_password = ""
        config.save(cfg)
        log("Cleared MariaDB root password from config.")
    log("MariaDB removed.")


def get_root_password() -> str:
    """Return the saved root password, preferring config but falling back to root.pw."""
    cfg = config.load()
    if cfg.mariadb.root_password:
        return cfg.mariadb.root_password
    p = _root_pw_file()
    if p.is_file():
        pw = p.read_text().strip()
        if pw:
            # Heal config for next time.
            cfg.mariadb.root_password = pw
            config.save(cfg)
            return pw
    return ""


def _init_datadir(my_cnf: Path, log: Log) -> None:
    """Initialize the datadir using `mariadb-install-db` (MariaDB's bootstrap script).

    `mysqld --initialize-insecure` is a MySQL option; MariaDB's mysqld does not
    accept it. The supported path is the `mariadb-install-db` wrapper. We must
    NOT pass `--defaults-file` since that script does its own option parsing
    and rejects mysqld-only options.
    """
    user = _current_user()
    script = paths.MARIADB_DIST / "scripts" / "mariadb-install-db"
    if not script.is_file():
        # Older tarballs name it mysql_install_db
        script = paths.MARIADB_DIST / "scripts" / "mysql_install_db"
    if not script.is_file():
        raise RuntimeError(
            f"Could not find mariadb-install-db under {paths.MARIADB_DIST}/scripts"
        )
    cmd = [
        str(script),
        f"--basedir={paths.MARIADB_DIST}",
        f"--datadir={paths.MARIADB_DATA}",
        f"--user={user}",
        "--auth-root-authentication-method=normal",
        "--skip-test-db",
    ]
    log("Initializing datadir with mariadb-install-db")
    _run_with_hints(cmd, log)


def _current_user() -> str:
    import getpass
    try:
        return getpass.getuser()
    except Exception:
        return "nobody"


def _set_root_password(my_cnf: Path, password: str, log: Log) -> None:
    """Apply a root password by piping ALTER USER to mysqld --bootstrap (no network).

    `--bootstrap` implies `--skip-grant-tables`, which blocks ALTER USER with
    error 1290. The first `FLUSH PRIVILEGES` re-enables the grant tables so
    the subsequent ALTER USER works.
    """
    pw_escaped = password.replace("\\", "\\\\").replace("'", "\\'")
    sql = (
        f"FLUSH PRIVILEGES;\n"
        f"ALTER USER 'root'@'localhost' IDENTIFIED BY '{pw_escaped}';\n"
        # TCP clients (dblab etc.) authenticate as 'root'@'127.0.0.1', a
        # distinct account in MariaDB. Create it if missing and give it the
        # same password + grants.
        f"CREATE USER IF NOT EXISTS 'root'@'127.0.0.1' IDENTIFIED BY '{pw_escaped}';\n"
        f"ALTER USER 'root'@'127.0.0.1' IDENTIFIED BY '{pw_escaped}';\n"
        f"GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION;\n"
        f"CREATE USER IF NOT EXISTS 'root'@'::1' IDENTIFIED BY '{pw_escaped}';\n"
        f"ALTER USER 'root'@'::1' IDENTIFIED BY '{pw_escaped}';\n"
        f"GRANT ALL PRIVILEGES ON *.* TO 'root'@'::1' WITH GRANT OPTION;\n"
        f"DELETE FROM mysql.global_priv WHERE User='';\n"
        f"DROP DATABASE IF EXISTS test;\n"
        f"FLUSH PRIVILEGES;\n"
    )
    user = _current_user()
    cmd = [
        str(_bin("mysqld")),
        "--no-defaults",
        f"--basedir={paths.MARIADB_DIST}",
        f"--datadir={paths.MARIADB_DATA}",
        f"--user={user}",
        "--bootstrap",
        "--skip-networking",
    ]
    log("Setting root password via mysqld --bootstrap")
    proc = subprocess.Popen(
        cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True,
    )
    out, _ = proc.communicate(sql)
    for line in (out or "").splitlines():
        log("  " + line.rstrip())
    if proc.returncode != 0:
        _emit_dep_hint(out or "", log)
        raise RuntimeError(f"mysqld --bootstrap failed (exit {proc.returncode})")


def _run(cmd: list[str], log: Log) -> None:
    log(f"$ {' '.join(cmd)}")
    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1,
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        log("  " + line.rstrip())
    rc = proc.wait()
    if rc != 0:
        raise RuntimeError(f"command failed (exit {rc}): {' '.join(cmd)}")


def _run_with_hints(cmd: list[str], log: Log) -> None:
    """Like _run, but buffers output so we can scan it for known dep failures."""
    log(f"$ {' '.join(cmd)}")
    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1,
    )
    assert proc.stdout is not None
    buf: list[str] = []
    for line in proc.stdout:
        line = line.rstrip()
        buf.append(line)
        log("  " + line)
    rc = proc.wait()
    if rc != 0:
        _emit_dep_hint("\n".join(buf), log)
        raise RuntimeError(f"command failed (exit {rc}): {' '.join(cmd)}")


def _emit_dep_hint(output: str, log: Log) -> None:
    low = output.lower()
    hints: list[str] = []
    if "libaio" in low:
        hints.append("missing libaio — install with:  sudo apt install -y libaio1")
    if "libncurses" in low or "libtinfo" in low:
        hints.append("missing libncurses — install with:  sudo apt install -y libncurses5 libtinfo5")
    if "libssl" in low or "libcrypto" in low:
        hints.append("missing OpenSSL libs — install with:  sudo apt install -y libssl-dev")
    if "no such file or directory" in low and "ld-linux" in low:
        hints.append("dynamic loader missing — the tarball architecture may not match this system")
    if hints:
        log("")
        log("HINT: MariaDB needs extra shared libraries on this host:")
        for h in hints:
            log("  - " + h)


# ---------- DB / user provisioning for pools ----------

def _mysql_cmd() -> list[str]:
    client = _bin("mariadb")
    if not client.exists():
        client = _bin("mysql")
    if not client.exists():
        raise RuntimeError("No mariadb/mysql client found in dist")
    return [str(client), "--protocol=SOCKET", f"--socket={paths.MARIADB_DIR / 'mysql.sock'}"]


def _exec_sql(root_password: str, sql: str, log: Log) -> None:
    cmd = _mysql_cmd() + ["-uroot", f"-p{root_password}"]
    log(f"$ {' '.join(cmd[:-1])} -p***")
    proc = subprocess.Popen(
        cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True,
    )
    out, _ = proc.communicate(sql)
    for line in (out or "").splitlines():
        log("  " + line.rstrip())
    if proc.returncode != 0:
        raise RuntimeError(f"mysql client failed (exit {proc.returncode})")


def wait_until_ready(timeout: float = 30.0) -> bool:
    sock = paths.MARIADB_DIR / "mysql.sock"
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if sock.exists():
            return True
        time.sleep(0.3)
    return False


def provision_database(db_name: str, db_user: str, log: Log, *,
                       db_password: str | None = None) -> str:
    """Create database + user if missing. Returns the (possibly generated) password."""
    if not is_installed():
        raise RuntimeError("MariaDB is not installed yet.")
    from ..instances.service import MariaDBInstance
    from ..supervisor import Status

    cfg = config.load()
    root_pw = get_root_password()
    if not root_pw:
        raise RuntimeError("MariaDB root password not set — reinstall MariaDB.")

    mariadb = MariaDBInstance(cfg)
    started_here = False
    if mariadb.status().status != Status.RUNNING:
        log("Starting MariaDB to provision database...")
        mariadb.start()
        started_here = True
        if not wait_until_ready():
            raise RuntimeError("MariaDB did not become ready in time")

    password = db_password or secrets.token_urlsafe(18)
    sql = (
        f"CREATE DATABASE IF NOT EXISTS `{db_name}` "
        f"CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n"
        f"CREATE USER IF NOT EXISTS '{db_user}'@'{cfg.mariadb.host}' "
        f"IDENTIFIED BY '{password}';\n"
        f"ALTER USER '{db_user}'@'{cfg.mariadb.host}' IDENTIFIED BY '{password}';\n"
        f"GRANT ALL PRIVILEGES ON `{db_name}`.* TO '{db_user}'@'{cfg.mariadb.host}';\n"
        f"FLUSH PRIVILEGES;\n"
    )
    _exec_sql(root_pw, sql, log)
    log(f"Provisioned database '{db_name}' and user '{db_user}'.")

    if started_here:
        log("(leaving MariaDB running)")

    return password
