"""Install the shared PyPlanet and create individual pools."""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Callable

from .. import config, paths, python38
from ..instances.pool import PoolMeta

Log = Callable[[str], None]


def _run(cmd: list[str], log: Log, cwd: Path | None = None) -> None:
    log(f"$ {' '.join(cmd)}")
    proc = subprocess.Popen(
        cmd,
        cwd=str(cwd) if cwd else None,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        log("  " + line.rstrip())
    rc = proc.wait()
    if rc != 0:
        raise RuntimeError(f"command failed (exit {rc}): {' '.join(cmd)}")


def is_installed() -> bool:
    return (paths.PYPLANET_VENV / "bin" / "pyplanet").is_file()


def install_pyplanet(log: Log) -> None:
    cfg = config.load()
    if is_installed():
        log("PyPlanet already installed.")
        return

    py = python38.ensure_python38(log)
    log(f"Using Python: {py}")

    paths.PYPLANET_DIR.mkdir(parents=True, exist_ok=True)

    if not (paths.PYPLANET_SRC / ".git").exists():
        if paths.PYPLANET_SRC.exists():
            log(f"Removing non-git dir at {paths.PYPLANET_SRC}")
            shutil.rmtree(paths.PYPLANET_SRC)
        _run(["git", "clone", cfg.downloads.pyplanet_git, str(paths.PYPLANET_SRC)], log)
    else:
        log("Updating existing PyPlanet clone")
        _run(["git", "-C", str(paths.PYPLANET_SRC), "fetch", "--tags"], log)

    ref = cfg.downloads.pyplanet_ref
    if ref == "latest-release":
        out = subprocess.run(
            ["git", "-C", str(paths.PYPLANET_SRC), "tag", "--sort=-v:refname"],
            check=True, capture_output=True, text=True,
        )
        tags = [t for t in out.stdout.splitlines() if t.strip()]
        if not tags:
            raise RuntimeError("PyPlanet repo has no tags")
        ref = tags[0]
        log(f"Latest release tag: {ref}")
    _run(["git", "-C", str(paths.PYPLANET_SRC), "checkout", ref], log)

    if not paths.PYPLANET_VENV.exists():
        _run([str(py), "-m", "venv", str(paths.PYPLANET_VENV)], log)
    pip = paths.PYPLANET_VENV / "bin" / "pip"
    _run([str(pip), "install", "--upgrade", "pip", "setuptools", "wheel"], log)
    req = paths.PYPLANET_SRC / "requirements.txt"
    if req.is_file():
        _run([str(pip), "install", "-r", str(req)], log)
    _run([str(pip), "install", "-e", str(paths.PYPLANET_SRC)], log)
    log("PyPlanet installed.")


_SETTINGS_INIT = '''\
"""Auto-generated by tmsm. Imports all settings files in this directory."""
from .base import *
from .apps import *

try:
    from .local import *
except Exception:
    pass
'''

_SETTINGS_BASE_TEMPLATE = '''\
"""Auto-generated by tmsm for pool {pool_name}. Edit to customise."""
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
POOL_ROOT = os.path.dirname(ROOT)

DEBUG = False
OWNERS = {{"default": []}}

DEDICATED = {{
    "default": {{
        "HOST": "127.0.0.1",
        "PORT": {xmlrpc_port},
        "USER": "SuperAdmin",
        "PASSWORD": "{super_pw}",
    }}
}}

MAP_MATCHSETTINGS = {{"default": "MatchSettings/example.txt"}}

DATABASES = {{
    "default": {{
        "ENGINE": "peewee_async.MySQLDatabase",
        "NAME": "{db_name}",
        "OPTIONS": {{
            "host": "{db_host}",
            "port": {db_port},
            "user": "{db_user}",
            "password": "{db_password}",
            "charset": "utf8mb4",
            # Disable FK checks at connection time so peewee\'s first-run
            # create_tables() doesn\'t fail on errno 150 when a child table
            # (e.g. karma) is created before its parent. InnoDB still
            # enforces FKs at runtime via the storage engine.
            "init_command": "SET SESSION FOREIGN_KEY_CHECKS=0",
        }},
    }}
}}

STORAGE = {{
    "default": {{
        "DRIVER": "pyplanet.core.storage.drivers.local.LocalDriver",
        "OPTIONS": {{}},
    }}
}}

LOGGING_DIRECTORY = os.path.join(POOL_ROOT, "logs")
TMP_PATH = os.path.join(POOL_ROOT, "tmp")
LOGGING = {{
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {{
        "default": {{"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"}},
    }},
    "handlers": {{
        "console": {{"class": "logging.StreamHandler", "formatter": "default"}},
    }},
    "root": {{"handlers": ["console"], "level": "INFO"}},
}}

TIMEZONE = "UTC"
'''

_SETTINGS_APPS_TEMPLATE = '''\
"""Apps loaded for pool {pool_name}. Add or remove contrib apps here."""

# These are added *after* the mandatory core apps (core.pyplanet,
# core.maniaplanet, core.trackmania, …) which PyPlanet always loads.
APPS = {{
    "default": [
        "pyplanet.apps.contrib.admin",
        "pyplanet.apps.contrib.jukebox",
        "pyplanet.apps.contrib.karma",
        "pyplanet.apps.contrib.local_records",
        "pyplanet.apps.contrib.players",
        "pyplanet.apps.contrib.info",
        "pyplanet.apps.contrib.mx",
        "pyplanet.apps.contrib.transactions",
        "pyplanet.apps.contrib.clock",
        "pyplanet.apps.contrib.funcmd",
    ]
}}
'''


def create_pool(name: str, target_server: str, super_pw: str, xmlrpc_port: int, log: Log) -> Path:
    if not is_installed():
        raise RuntimeError("PyPlanet is not installed yet — install it first.")
    cfg = config.load()
    root = paths.PYPLANET_POOLS / name
    if root.exists():
        raise FileExistsError(f"Pool '{name}' already exists at {root}")

    (root / "settings").mkdir(parents=True, exist_ok=True)
    (root / "logs").mkdir(exist_ok=True)
    (root / "tmp").mkdir(exist_ok=True)

    db_name = f"pyplanet_{name.replace('-', '_')}"
    db_user = f"pp_{name.replace('-', '_')}"[:32]
    db_password = ""

    # If MariaDB is installed, provision the DB + user and capture the password.
    from . import mariadb as mariadb_installer
    if mariadb_installer.is_installed():
        log("Provisioning database in MariaDB...")
        db_password = mariadb_installer.provision_database(db_name, db_user, log)
    else:
        log("NOTE: MariaDB is not installed yet. Pool settings will have an empty DB password.")
        log("      Install MariaDB and then re-create the pool, or edit settings/base.py manually.")

    (root / "settings" / "__init__.py").write_text(_SETTINGS_INIT)
    (root / "settings" / "base.py").write_text(_SETTINGS_BASE_TEMPLATE.format(
        pool_name=name,
        xmlrpc_port=xmlrpc_port,
        super_pw=super_pw,
        db_name=db_name,
        db_host=cfg.mariadb.host,
        db_port=cfg.mariadb.port,
        db_user=db_user,
        db_password=db_password,
    ))
    (root / "settings" / "apps.py").write_text(_SETTINGS_APPS_TEMPLATE.format(
        pool_name=name,
    ))
    log(f"Wrote settings for pool '{name}'")

    PoolMeta(
        name=name,
        target_server=target_server,
        db_name=db_name,
        db_user=db_user,
        db_password=db_password,
        settings_module="settings",
    ).save(root)
    log(f"Pool '{name}' created at {root}")
    return root


def delete_pool(name: str, log: Log) -> None:
    root = paths.PYPLANET_POOLS / name
    if not root.exists():
        raise FileNotFoundError(f"Pool '{name}' not found at {root}")
    log(f"Removing {root}")
    shutil.rmtree(root)
    log(f"Pool '{name}' deleted.")
